'use client'
/**
 * src/components/reports/CAReportButton.tsx
 *
 * Reusable CA Report generation button + panel.
 * Add this to ANY report page (Payments, Daily, Monthly, Insurance Claims).
 *
 * Features:
 *   - Print-optimized PDF with headers/footers
 *   - Email via API (Resend) or fallback
 *   - WhatsApp share
 *   - Period selection
 *
 * Usage:
 *   <CAReportButton reportData={data} title="Patient Payment Report" />
 */

import { useState } from 'react'
import { supabase } from '@/lib/supabase'
import { getHospitalSettings } from '@/lib/utils'
import { loadSettings } from '@/lib/settings'
import { FileText, Printer, Mail, MessageCircle, Download, ChevronDown, ChevronUp, Loader2 } from 'lucide-react'

interface CAReportData {
  title: string
  period: string
  fromDate: string
  toDate: string
  summaryRows: { label: string; value: string }[]
  tableHeaders: string[]
  tableRows: string[][]
  totalRow?: string[]
}

interface CAReportButtonProps {
  reportData: CAReportData | null
  onGenerate?: () => void
  loading?: boolean
}

export default function CAReportButton({ reportData, onGenerate, loading }: CAReportButtonProps) {
  const [expanded, setExpanded] = useState(false)
  const [sending, setSending] = useState(false)
  const [sentMsg, setSentMsg] = useState('')

  const hs = typeof window !== 'undefined' ? getHospitalSettings() : {} as any
  const settings = typeof window !== 'undefined' ? loadSettings() : { caName: '', caWhatsApp: '', caEmail: '' }

  function handlePrint() {
    if (!reportData) return

    const html = buildPrintHTML(reportData, hs)
    const w = window.open('', '_blank')
    if (w) {
      w.document.write(html)
      w.document.close()
      setTimeout(() => w.print(), 500)
    }
  }

  async function handleEmail() {
    if (!reportData || !settings.caEmail) return
    setSending(true)
    setSentMsg('')

    try {
      const { data: { session } } = await supabase.auth.getSession()
      const res = await fetch('/api/billing/send-email', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(session?.access_token ? { Authorization: `Bearer ${session.access_token}` } : {}),
        },
        body: JSON.stringify({
          recipientEmail: settings.caEmail,
          recipientName: settings.caName || 'CA',
          reportData: {
            period: reportData.period,
            fromDate: reportData.fromDate,
            toDate: reportData.toDate,
            totalGross: 0,
            totalDiscount: 0,
            totalNet: 0,
            billCount: 0,
            pendingCount: 0,
            pendingAmount: 0,
            paymentBreakdown: [],
            serviceBreakdown: [],
          },
          hospitalSettings: hs,
        }),
      })
      const data = await res.json()
      if (data.success && data.method === 'email') {
        setSentMsg(`Sent to ${settings.caEmail}`)
      } else {
        setSentMsg(data.message || 'Configure RESEND_API_KEY in environment')
      }
    } catch (err: any) {
      setSentMsg('Failed: ' + err.message)
    }
    setSending(false)
    setTimeout(() => setSentMsg(''), 5000)
  }

  function handleWhatsApp() {
    if (!reportData || !settings.caWhatsApp) return
    const msg = encodeURIComponent(
      `*${hs.hospitalName || 'Hospital'} — ${reportData.title}*\n` +
      `Period: ${reportData.period}\n\n` +
      reportData.summaryRows.map(r => `${r.label}: ${r.value}`).join('\n') +
      `\n\n_Generated by NexMedicon HMS_`
    )
    window.open(`https://wa.me/${settings.caWhatsApp.replace(/\D/g, '')}?text=${msg}`, '_blank')
  }

  return (
    <div className="inline-flex flex-col">
      <button
        onClick={() => {
          setExpanded(!expanded)
          if (!expanded && onGenerate) onGenerate()
        }}
        className={`flex items-center gap-2 text-xs font-semibold px-3 py-2 rounded-xl transition-colors ${
          expanded ? 'bg-purple-600 text-white' : 'bg-purple-50 text-purple-700 border border-purple-200 hover:bg-purple-100'
        }`}
      >
        <FileText className="w-3.5 h-3.5" />
        CA Report
        {expanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
      </button>

      {expanded && (
        <div className="mt-2 bg-white border border-purple-200 rounded-xl p-4 shadow-lg min-w-[280px]">
          {loading && (
            <div className="flex items-center gap-2 text-sm text-gray-500 py-4 justify-center">
              <Loader2 className="w-4 h-4 animate-spin" /> Generating report...
            </div>
          )}

          {!loading && !reportData && (
            <p className="text-xs text-gray-400 text-center py-3">
              No report data available. Apply filters first.
            </p>
          )}

          {!loading && reportData && (
            <div className="space-y-3">
              <div className="text-xs font-bold text-purple-700 uppercase tracking-wide">
                {reportData.title} — {reportData.period}
              </div>

              {/* Summary */}
              <div className="grid grid-cols-2 gap-2">
                {reportData.summaryRows.slice(0, 4).map(r => (
                  <div key={r.label} className="bg-gray-50 rounded-lg px-2 py-1.5 text-center">
                    <div className="text-xs font-bold text-gray-700">{r.value}</div>
                    <div className="text-[9px] text-gray-400">{r.label}</div>
                  </div>
                ))}
              </div>

              {/* Action buttons */}
              <div className="flex gap-2 flex-wrap pt-2 border-t border-gray-100">
                <button onClick={handlePrint}
                  className="flex items-center gap-1 text-xs bg-gray-50 text-gray-700 border border-gray-200 rounded-lg px-2.5 py-1.5 hover:bg-gray-100">
                  <Printer className="w-3 h-3" /> Print PDF
                </button>
                {settings.caEmail && (
                  <button onClick={handleEmail} disabled={sending}
                    className="flex items-center gap-1 text-xs bg-blue-50 text-blue-700 border border-blue-200 rounded-lg px-2.5 py-1.5 hover:bg-blue-100 disabled:opacity-50">
                    <Mail className="w-3 h-3" /> {sending ? 'Sending...' : 'Email CA'}
                  </button>
                )}
                {settings.caWhatsApp && (
                  <button onClick={handleWhatsApp}
                    className="flex items-center gap-1 text-xs bg-green-50 text-green-700 border border-green-200 rounded-lg px-2.5 py-1.5 hover:bg-green-100">
                    <MessageCircle className="w-3 h-3" /> WhatsApp
                  </button>
                )}
              </div>
              {sentMsg && (
                <p className="text-xs text-blue-600 mt-1">{sentMsg}</p>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  )
}

// ── Build professional print HTML ─────────────────────────────
function buildPrintHTML(data: CAReportData, hs: any): string {
  const summaryHTML = data.summaryRows
    .map(r => `<div class="summary-box"><div class="value">${r.value}</div><div class="label">${r.label}</div></div>`)
    .join('')

  const headerRow = data.tableHeaders.map(h => `<th>${h}</th>`).join('')
  const bodyRows = data.tableRows
    .map(row => `<tr>${row.map(cell => `<td>${cell}</td>`).join('')}</tr>`)
    .join('')
  const totalRowHTML = data.totalRow
    ? `<tr class="total-row">${data.totalRow.map(cell => `<td><strong>${cell}</strong></td>`).join('')}</tr>`
    : ''

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${data.title} — ${hs.hospitalName || 'NexMedicon'}</title>
<style>
  body { font-family: 'Inter', Arial, sans-serif; color: #1e293b; margin: 0; padding: 30px 40px; font-size: 11px; }
  .header { text-align: center; border-bottom: 3px solid #1e40af; padding-bottom: 12px; margin-bottom: 20px; }
  .header h1 { font-size: 20px; color: #1e40af; margin: 0 0 2px; font-weight: 800; }
  .header p { font-size: 10px; color: #64748b; margin: 2px 0; }
  .title { font-size: 14px; font-weight: 700; margin-bottom: 4px; }
  .subtitle { font-size: 10px; color: #64748b; margin-bottom: 16px; }
  .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(100px, 1fr)); gap: 8px; margin-bottom: 20px; }
  .summary-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px; text-align: center; }
  .summary-box .value { font-size: 14px; font-weight: 700; color: #1e293b; }
  .summary-box .label { font-size: 8px; color: #64748b; text-transform: uppercase; margin-top: 2px; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 10px; }
  th { background: #1e40af; color: white; padding: 6px 10px; text-align: left; font-size: 9px; text-transform: uppercase; }
  td { padding: 6px 10px; border-bottom: 1px solid #f1f5f9; }
  tr:nth-child(even) td { background: #f8fafc; }
  .total-row td { border-top: 2px solid #1e293b; font-weight: bold; background: #f1f5f9 !important; }
  .footer { margin-top: 24px; padding-top: 10px; border-top: 2px solid #1e40af; font-size: 9px; color: #94a3b8; display: flex; justify-content: space-between; }
  @media print { body { padding: 15px; } @page { margin: 10mm; } }
</style></head><body>
  <div class="header">
    <h1>${hs.hospitalName || 'NexMedicon Hospital'}</h1>
    ${hs.address && hs.address !== 'Your Hospital Address, City, PIN' ? `<p>${hs.address}</p>` : ''}
    ${hs.phone ? `<p>Tel: ${hs.phone}</p>` : ''}
  </div>
  <div class="title">${data.title}</div>
  <div class="subtitle">Period: ${data.period} (${data.fromDate} to ${data.toDate})</div>
  <div class="summary-grid">${summaryHTML}</div>
  <table><thead><tr>${headerRow}</tr></thead><tbody>${bodyRows}${totalRowHTML}</tbody></table>
  <div class="footer">
    <span>Generated: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })} at ${new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}</span>
    <span>${hs.hospitalName || 'NexMedicon HMS'}</span>
  </div>
</body></html>`
}

export type { CAReportData }