/**
 * /api/parse-pdf
 *
 * Dedicated PDF parser for fillable patient registration PDFs.
 *
 * Strategy (in order):
 *   1. pdf-lib  — reads AcroForm field values directly (100% accurate, no AI key)
 *   2. pdf-parse + AI — extracts text layer then sends to AI for structuring
 *   3. Clear error if the PDF is a scanned image (no text layer, no fields)
 *
 * POST body: multipart/form-data
 *   file: File (application/pdf)
 *   form_type: string (optional hint)
 */
import { NextRequest, NextResponse } from 'next/server'
import { PDFDocument } from 'pdf-lib'
import { analyzePDF, hasAnyAIKey } from '@/lib/ai-client'

const SYSTEM_PROMPT = `You are a medical form parser for Indian hospitals.
Extract all patient information from the following PDF text into a JSON object.

Return ONLY valid JSON with this structure (omit empty fields):
{
  "form_type": "patient_registration",
  "confidence": "high|medium|low",
  "patient": {
    "full_name": "",
    "date_of_birth": "YYYY-MM-DD",
    "age": "",
    "gender": "Female|Male|Other",
    "mobile": "",
    "blood_group": "A+|A-|B+|B-|O+|O-|AB+|AB-",
    "address": "",
    "abha_id": "",
    "emergency_contact_name": "",
    "emergency_contact_phone": ""
  },
  "insurance": {
    "mediclaim": "Yes|No",
    "cashless": "Yes|No",
    "company": ""
  },
  "reference_source": "",
  "chief_complaint": ""
}
Return ONLY valid JSON. No markdown. No explanation.`

export async function POST(req: NextRequest) {
  try {
    const fd       = await req.formData()
    const file     = fd.get('file') as File | null
    const formType = (fd.get('form_type') as string | null) ?? 'patient_registration'

    if (!file) return NextResponse.json({ error: 'No file provided.' })
    if (file.type !== 'application/pdf') return NextResponse.json({ error: 'Only PDF files are accepted.' })
    if (file.size > 20 * 1024 * 1024) return NextResponse.json({ error: 'File too large. Max 20 MB.' })

    const bytes = Buffer.from(await file.arrayBuffer())

    // ── STRATEGY 1: Read AcroForm fields with pdf-lib ──────────────
    // This works perfectly for our fillable PDF (generated by /api/generate-pdf)
    try {
      const pdfDoc = await PDFDocument.load(bytes, { ignoreEncryption: true })
      const form   = pdfDoc.getForm()
      const fields = form.getFields()

      if (fields.length > 0) {
        const raw: Record<string, string> = {}

        for (const field of fields) {
          const name = field.getName()
          try {
            // TextField
            const tf = form.getTextField(name)
            const val = tf.getText()?.trim()
            if (val) raw[name] = val
          } catch { /* not a text field */ }
          try {
            // RadioGroup
            const rg = form.getRadioGroup(name)
            const val = rg.getSelected()?.trim()
            if (val) raw[name] = val
          } catch { /* not a radio group */ }
          try {
            // CheckBox
            const cb = form.getCheckBox(name)
            raw[name] = cb.isChecked() ? 'Yes' : 'No'
          } catch { /* not a checkbox */ }
        }

        // Map raw field names to our structured format
        const patient: Record<string, string> = {}
        if (raw.full_name)               patient.full_name               = raw.full_name
        if (raw.date_of_birth)           patient.date_of_birth           = normDate(raw.date_of_birth)
        if (raw.age)                     patient.age                     = raw.age
        if (raw.gender)                  patient.gender                  = raw.gender
        if (raw.mobile)                  patient.mobile                  = raw.mobile.replace(/\D/g,'').slice(-10)
        if (raw.blood_group)             patient.blood_group             = raw.blood_group
        if (raw.address)                 patient.address                 = raw.address
        if (raw.aadhaar || raw.abha_id)  patient.abha_id                 = raw.aadhaar || raw.abha_id
        if (raw.emergency_contact_name)  patient.emergency_contact_name  = raw.emergency_contact_name
        if (raw.emergency_contact_phone) patient.emergency_contact_phone = raw.emergency_contact_phone.replace(/\D/g,'').slice(-10)

        const result: any = {
          form_type:          formType,
          confidence:         'high',
          language_detected:  'English',
          raw_text:           JSON.stringify(raw),
          _provider:          'pdf-lib/acroform-fields',
          patient,
        }

        if (raw.mediclaim || raw.cashless || raw.insurance_company) {
          result.insurance = {
            mediclaim: raw.mediclaim || 'No',
            cashless:  raw.cashless  || 'No',
            company:   raw.insurance_company || '',
          }
          // Also store mediclaim in patient vitals for compatibility
          result.vitals = {
            ...(result.vitals || {}),
          }
        }

        if (raw.reference_source) result.reference_source = raw.reference_source
        if (raw.chief_complaint)  result.vitals = { ...(result.vitals||{}), chief_complaint: raw.chief_complaint }

        return NextResponse.json(result)
      }
    } catch (pdfLibErr: any) {
      console.warn('[parse-pdf] pdf-lib failed:', pdfLibErr.message?.slice(0, 80))
    }

    // ── STRATEGY 2: pdf-parse text extraction + AI ─────────────────
    // For non-AcroForm PDFs (typed text, digital fill without form fields)
    if (!hasAnyAIKey()) {
      return NextResponse.json({
        error: 'This PDF has no form fields. AI parsing requires OPENAI_API_KEY or ANTHROPIC_API_KEY in Vercel environment variables.',
      })
    }

    const base64 = bytes.toString('base64')
    const result = await analyzePDF({
      base64,
      prompt:    `Extract all patient registration fields from this PDF. Form type: ${formType}. Return JSON only.`,
      system:    SYSTEM_PROMPT,
      maxTokens: 1024,
    })

    const clean = result.text
      .replace(/^```json\s*/im, '').replace(/^```\s*/im, '').replace(/\s*```$/im, '').trim()

    try {
      const parsed = JSON.parse(clean)
      parsed._provider = result.provider
      return NextResponse.json(parsed)
    } catch {
      return NextResponse.json({
        form_type:  formType,
        confidence: 'low',
        raw_text:   result.text,
        _provider:  result.provider,
      })
    }

  } catch (err: any) {
    console.error('[parse-pdf]', err?.message)
    if (err?.message?.includes('no text layer') || err?.message?.includes('scanned')) {
      return NextResponse.json({
        error: 'This PDF is a scanned image and has no text. Please take a photo with your camera instead.',
      })
    }
    return NextResponse.json({ error: `PDF parsing failed: ${err?.message}` })
  }
}

function normDate(raw: string): string {
  // Convert DD/MM/YYYY or DD-MM-YYYY to YYYY-MM-DD
  const m = raw.match(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})/)
  if (!m) return raw
  const [, d, mo, y] = m
  const year = y.length === 2 ? '20' + y : y
  return `${year}-${mo.padStart(2,'0')}-${d.padStart(2,'0')}`
}
