'use client'
/**
 * src/app/portal/page.tsx
 *
 * Patient Portal Entry Point
 *
 * This page handles two flows:
 * 1. Legacy magic-link: /portal?mrn=P-001&token=xxx (backward compatible)
 * 2. New flow: redirects to /portal/login or /portal/dashboard based on session
 *
 * The legacy flow validates the old portal_tokens table and creates a new session.
 * The new flow uses portal_sessions with OTP-based login.
 */

import { useEffect, useState, Suspense } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { Heart, AlertCircle } from 'lucide-react'

function PortalEntryContent() {
  const router = useRouter()
  const params = useSearchParams()
  const mrn    = params.get('mrn')
  const token  = params.get('token')

  const [status, setStatus] = useState<'checking' | 'error'>('checking')
  const [error, setError]   = useState('')

  useEffect(() => {
    // If legacy magic link params present, verify via old token system
    if (mrn && token) {
      verifyLegacyToken(mrn, token)
      return
    }

    // Check if already logged in
    const session = localStorage.getItem('portal_session')
    if (session) {
      router.replace('/portal/dashboard')
    } else {
      router.replace('/portal/login')
    }
  }, [mrn, token])

  async function verifyLegacyToken(mrn: string, token: string) {
    try {
      // Use the verify-otp endpoint with the token (it handles both magic link tokens)
      const res = await fetch('/api/portal/auth/verify-otp', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token }),
      })

      if (res.ok) {
        const data = await res.json()
        localStorage.setItem('portal_session', data.session_token)
        localStorage.setItem('portal_patient', JSON.stringify(data.patient))
        router.replace('/portal/dashboard')
        return
      }

      // If new token system fails, try legacy validation
      // (for tokens generated by the old /api/portal/send-link route)
      const legacyRes = await fetch('/api/portal/legacy-verify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ mrn, token }),
      })

      if (legacyRes.ok) {
        const data = await legacyRes.json()
        localStorage.setItem('portal_session', data.session_token)
        localStorage.setItem('portal_patient', JSON.stringify(data.patient))
        router.replace('/portal/dashboard')
      } else {
        setError('This link has expired or is invalid. Please request a new one.')
        setStatus('error')
      }
    } catch {
      setError('Network error. Please check your connection.')
      setStatus('error')
    }
  }

  if (status === 'error') {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <div className="bg-white rounded-2xl shadow-lg p-8 max-w-sm w-full text-center">
          <AlertCircle className="w-12 h-12 text-red-400 mx-auto mb-4"/>
          <h2 className="text-xl font-bold text-gray-800 mb-2">Invalid or Expired Link</h2>
          <p className="text-gray-500 text-sm mb-4">{error}</p>
          <button
            onClick={() => router.push('/portal/login')}
            className="w-full bg-blue-600 text-white rounded-xl py-3 font-semibold hover:bg-blue-700">
            Login with Mobile Number
          </button>
          <p className="text-xs text-gray-400 mt-4">
            Links expire after 24 hours for your security.
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center">
      <div className="text-center">
        <div className="w-12 h-12 border-4 border-blue-400 border-t-transparent rounded-full animate-spin mx-auto mb-4"/>
        <p className="text-gray-600 font-medium">Loading your health portal…</p>
      </div>
    </div>
  )
}

export default function PortalPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="w-10 h-10 border-4 border-blue-400 border-t-transparent rounded-full animate-spin"/>
      </div>
    }>
      <PortalEntryContent/>
    </Suspense>
  )
}
