/**
 * src/app/api/portal/legacy-verify/route.ts
 *
 * Legacy Portal Token Verification
 *
 * Handles old-style portal tokens from the portal_tokens table
 * (generated by /api/portal/send-link). Creates a new portal_session
 * so the patient can use the new dashboard.
 */

import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const serviceKey  = process.env.SUPABASE_SERVICE_ROLE_KEY!

export async function POST(req: NextRequest) {
  try {
    const { mrn, token } = await req.json()

    if (!mrn || !token) {
      return NextResponse.json({ error: 'mrn and token are required' }, { status: 400 })
    }

    const supabase = createClient(supabaseUrl, serviceKey, { auth: { persistSession: false } })

    // Validate legacy portal token
    const { data: portalToken } = await supabase
      .from('portal_tokens')
      .select('id, mrn, patient_id, expires_at, is_used')
      .eq('mrn', mrn)
      .eq('token', token)
      .single()

    if (!portalToken) {
      return NextResponse.json({ error: 'Invalid token' }, { status: 401 })
    }

    if (portalToken.is_used) {
      return NextResponse.json({ error: 'Token already used' }, { status: 401 })
    }

    if (new Date(portalToken.expires_at) < new Date()) {
      return NextResponse.json({ error: 'Token expired' }, { status: 401 })
    }

    // Mark token as used
    await supabase
      .from('portal_tokens')
      .update({ is_used: true })
      .eq('id', portalToken.id)

    // Get patient info
    const { data: patient } = await supabase
      .from('patients')
      .select('id, full_name, mrn, age, gender, mobile, blood_group')
      .eq('mrn', mrn)
      .single()

    if (!patient) {
      return NextResponse.json({ error: 'Patient not found' }, { status: 404 })
    }

    // Create a new portal session
    const sessionToken = crypto.randomUUID() + '-' + crypto.randomUUID()
    const sessionExpiry = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString()

    await supabase
      .from('portal_sessions')
      .insert({
        patient_id:    patient.id,
        mrn:           patient.mrn,
        mobile:        patient.mobile || '',
        session_token: sessionToken,
        expires_at:    sessionExpiry,
      })

    return NextResponse.json({
      success:       true,
      session_token: sessionToken,
      expires_at:    sessionExpiry,
      patient,
    })

  } catch (err: any) {
    console.error('Legacy verify error:', err)
    return NextResponse.json({ error: err.message || 'Internal error' }, { status: 500 })
  }
}
